version: '3.8'

services:
  qgroundcontrol:
    build:
      context: .
      dockerfile: qgc.dockerfile
    container_name: qgcappimagetest
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - ardupilot
    ports:
      - "14550:14550"  
    networks:
      - ardupilot-network

  ardupilot:
    build:
      context: .
      dockerfile: ardupilot.dockerfile  
    container_name: ardupilot
    #command: bash
    command: /home/ardupilot/Tools/autotest/sim_vehicle.py -v ArduCopter --no-mavproxy
    tty: true
    ports:
      - "5760:5760"   
    networks:
      - ardupilot-network
  
  wireshark:
    build:
      context: .
      dockerfile: wireshark.dockerfile  
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    network_mode: host
    # volumes:
    #   - ./wireshark/mavlink_2_common.lua:/usr/lib/wireshark/plugins
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 3000:3000 #optional
      - 3001:3001 #optional
    restart: unless-stopped

networks:
  ardupilot-network:
    driver: bridge
